# Generated by Django 2.2.3 on 2019-07-09 14:34

import Questions.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InputTextFile', models.FileField(upload_to=Questions.models.input_file_name)),
                ('OutputTextFile', models.FileField(upload_to=Questions.models.out_file_name)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_name', models.CharField(db_column='src_name', max_length=50, verbose_name='题目类型')),
                ('src_dec', models.TextField(db_column='src_dec', verbose_name='类型描述')),
            ],
            options={
                'verbose_name': '题目类型',
                'verbose_name_plural': '题目类型',
                'db_table': 'QuestionsType',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='id')),
                ('title', models.CharField(blank=True, db_column='title', default=None, max_length=50, null=True, unique=True, verbose_name='题名')),
                ('src', models.TextField(db_column='src', verbose_name='题目内容')),
                ('show_example', models.TextField(db_column='show_example', verbose_name='样例说明')),
                ('InputTextFile', models.FileField(upload_to=Questions.models.input_file_name)),
                ('OutputTextFile', models.FileField(upload_to=Questions.models.out_file_name)),
                ('difficult', models.IntegerField(db_column='difficult', verbose_name='难度系数')),
                ('time', models.IntegerField(db_column='time', verbose_name='时限毫秒')),
                ('memory', models.IntegerField(db_column='memory', verbose_name='内存k单位')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questions.QuestionsType', verbose_name='题目类型')),
            ],
            options={
                'verbose_name': '题库',
                'verbose_name_plural': '题库',
                'db_table': 'Questions',
            },
        ),
    ]
