# Generated by Django 2.2.3 on 2019-07-09 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExampleR',
        ),
    ]
