# Generated by Django 2.2.3 on 2019-07-10 10:55

import Questions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0002_delete_exampler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='InputTextFile',
            field=models.FileField(upload_to=Questions.models.input_file_name, verbose_name='输入文件'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='OutputTextFile',
            field=models.FileField(upload_to=Questions.models.out_file_name, verbose_name='输出文件'),
        ),
    ]
