# Generated by Django 2.2.3 on 2019-07-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_remove_users_src'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='icon',
            field=models.ImageField(default='avatar/default.png', height_field=80, upload_to='avatar/%Y/%m/%d', verbose_name='头像', width_field=80),
        ),
    ]
